name: test-action

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: test-action

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./
        with:
          chart-branch: chart-test
